name: Test

on:
  push: {branches: master}
  pull_request: {branches: master}
  repository_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        pair:
          # Full Versions
          - otp-version: 22.0
            elixir-version: 1.9.1
          - otp-version: 21.0
            elixir-version: 1.8.1
          - otp-version: 21.x
            elixir-version: <1.9.1
          - otp-version: 22.0
            elixir-version: master
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Use actions/setup-elixir
        uses: actions/setup-node@v1.2.0
        with:
          otp-version: ${{matrix.pair.otp-version}}
          elixir-version: ${{matrix.pair.elixir-version}}
      - name: Run Mix project tests
        run: |-
          mix deps.get
          mix test
          MIX_ENV=test mix dialyzer --halt-exit-status
          mix credo
          mix format --check-formatted
